### ISSUE TITLE
Missing function reference

### ISSUE THREAD

**Issue by yekenuk** [yekenuk/meal-tracker#69]
```
An error of type E_ERROR was caused in line 71 of the file /home/customer/www/calorie.sunrisediet.com/public_html/wp-content/plugins/meal-tracker/core/admin-pages/page.help.php. Error message: Uncaught Error: Call to undefined function ws_ls_create_dialog_jquery_code() in /home/customer/www/calorie.sunrisediet.com/public_html/wp-content/plugins/meal-tracker/core/admin-pages/page.help.php:71
Stack trace:
#0 /home/customer/www/calorie.sunrisediet.com/public_html/wp-includes/class-wp-hook.php(288): yk_mt_help_page('')
#1 /home/customer/www/calorie.sunrisediet.com/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /home/customer/www/calorie.sunrisediet.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/customer/www/calorie.sunrisediet.com/public_html/wp-admin/admin.php(254): do_action('meal-tracker_pa...')
#4 {main}
 thrown
```

**Comment by yekenuk** [comment]
https://github.com/yekenuk/meal-tracker/blob/f21d0bcb90d14cb60180c96138e894eb1d338e2e/core/admin-pages/page.help.php#L71

**Comment by yekenuk** [comment]
Ready for deploy
